version: '2'
services:
    lunchapplication-app:
        image: lunchapplication
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@lunchapplication-oracle:1521:LunchApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 7777:7777
